vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
vim.keymap.set("n", "<leader>gd", vim.cmd.Gdiff)
vim.keymap.set("n", "<leader>ga", vim.cmd.Gadd)
vim.keymap.set("n", "<leader>gc", vim.cmd.Gcommit)
vim.keymap.set("n", "<leader>gp", vim.cmd.Gpush)
vim.keymap.set("n", "<leader>gl", vim.cmd.Gpull)
